apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: leaderworkerset-on-delete-strategy
spec:
  rolloutStrategy:
    type: OnDelete
  replicas: 1
  leaderWorkerTemplate:
    leaderTemplate:
      spec:
        containers:
          - name: nginx
            image: anolis-registry.cn-zhangjiakou.cr.aliyuncs.com/openanolis/nginx:1.14.1-8.6
            resources:
              limits:
                cpu: "100m"
              requests:
                cpu: "50m"
            ports:
              - containerPort: 8080
    size: 2
    restartPolicy: None
    workerTemplate:
      spec:
        containers:
          - name: nginx
            image: anolis-registry.cn-zhangjiakou.cr.aliyuncs.com/openanolis/nginx:1.14.1-8.6
            command: [ "sh","-c","sleep 10s; exit 1" ]
            resources:
              limits:
                cpu: "100m"
              requests:
                cpu: "50m"
            ports:
              - containerPort: 8080
          